# Generated by Django 3.1.6 on 2023-09-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0315_auto_20230914_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='datehour',
            field=models.CharField(default='2023-09-23', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_credit_date',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='datehour',
            field=models.CharField(default='2023-09-23', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_credit_date',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='datehour',
            field=models.CharField(default='2023-09-23', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='last_credit_date',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='datehour',
            field=models.CharField(default='2023-09-23', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='last_debt_date',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2023-09-23', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2023-09-23', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datehour',
            field=models.CharField(default='2023-09-23', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Torneo')),
                ('datejoined', models.DateField(default='2023-09-23', max_length=10, verbose_name='Fecha')),
                ('status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tournament')),
            ],
            options={
                'verbose_name': 'Detalle de Torneo',
                'verbose_name_plural': 'Detalle de Torneos',
                'ordering': ['id'],
            },
        ),
    ]
