# Generated by Django 3.1.6 on 2023-09-24 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0316_auto_20230923_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confrontations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundNumber', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team1', to='crud.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Team2', to='crud.team')),
            ],
            options={
                'verbose_name': 'Enfrentamiento',
                'verbose_name_plural': 'Enfrentamientos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dettournament',
            name='earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dettournament',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dettournament',
            name='removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dettournament',
            name='tied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='datejoined',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='datehour',
            field=models.CharField(default='2023-09-24', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='last_credit_date',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='datehour',
            field=models.CharField(default='2023-09-24', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_credit_date',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='datehour',
            field=models.CharField(default='2023-09-24', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detcredit',
            name='last_credit_date',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='datehour',
            field=models.CharField(default='2023-09-24', max_length=30, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='detdebt',
            name='last_debt_date',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='dettournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.tournament'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2023-09-24', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2023-09-24', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datehour',
            field=models.CharField(default='2023-09-24', max_length=30, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datejoined',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='datejoined',
            field=models.DateField(default='2023-09-24', max_length=10, verbose_name='Fecha'),
        ),
        migrations.CreateModel(
            name='Ridding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundNumber', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.tournament')),
            ],
            options={
                'verbose_name': 'Equipo Librando',
                'verbose_name_plural': 'Equipos Librando',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetConfrontations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confrontation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.confrontations')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LosingTeam', to='crud.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='WinningTeam', to='crud.team')),
            ],
            options={
                'verbose_name': 'Detalle de Enfrentamiento',
                'verbose_name_plural': 'Detalle de Enfrentamientos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='confrontations',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.tournament'),
        ),
    ]
