# Generated by Django 3.1.6 on 2023-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0318_auto_20230924_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridding',
            name='roundNumber',
            field=models.IntegerField(default=0),
        ),
    ]
