# Generated by Django 3.1.6 on 2023-10-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0320_auto_20231004_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettournament',
            name='lastOpponent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lastOpponent', to='crud.team'),
            preserve_default=False,
        ),
    ]
