# Generated by Django 3.1.6 on 2023-10-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0321_dettournament_lastopponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettournament',
            name='lastOpponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lastOpponent', to='crud.team'),
        ),
    ]
