# Generated by Django 3.1.6 on 2023-10-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0323_auto_20231007_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettournament',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
