# Generated by Django 3.1.6 on 2023-10-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0325_dettournament_qtyround'),
    ]

    operations = [
        migrations.AddField(
            model_name='confrontations',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
