# Generated by Django 3.1.6 on 2023-10-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0326_confrontations_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dettournament',
            name='qtyRound',
        ),
        migrations.AddField(
            model_name='confrontations',
            name='qtyRound1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='confrontations',
            name='qtyRound2',
            field=models.IntegerField(default=0),
        ),
    ]
