# Generated by Django 3.1.6 on 2023-10-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0327_auto_20231007_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confrontations',
            name='qtyRound1',
        ),
        migrations.RemoveField(
            model_name='confrontations',
            name='qtyRound2',
        ),
        migrations.AddField(
            model_name='confrontations',
            name='qtyRound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dettournament',
            name='qtyRound',
            field=models.IntegerField(default=0),
        ),
    ]
