# Generated by Django 3.1.6 on 2023-10-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0329_auto_20231007_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettournament',
            name='plays',
            field=models.IntegerField(default=0),
        ),
    ]
