# Generated by Django 3.1.6 on 2023-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0331_auto_20231008_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='qtyLosses',
            field=models.IntegerField(default=0, verbose_name='Número de Pérdidas'),
        ),
    ]
