# Generated by Django 3.1.6 on 2023-10-08 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0332_auto_20231008_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettournament',
            name='lastOpponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastOpponent', to='crud.team'),
        ),
        migrations.AlterField(
            model_name='dettournament',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.team'),
        ),
        migrations.AlterField(
            model_name='dettournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tournament'),
        ),
    ]
