# Generated by Django 3.1.6 on 2023-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0333_auto_20231008_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
