# Generated by Django 3.1.6 on 2023-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0334_tournament_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
