# Generated by Django 3.1.6 on 2023-10-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0336_auto_20231008_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
