# Generated by Django 3.1.6 on 2024-01-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0337_auto_20231008_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2024-01-08', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2024-01-08', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='datejoined',
            field=models.DateField(default='2024-01-08', max_length=10, verbose_name='Fecha'),
        ),
    ]
