# Generated by Django 3.1.6 on 2024-01-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0339_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='birthdate',
            field=models.DateField(default='2024-01-09', max_length=50, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='team',
            name='dni',
            field=models.CharField(default='N/A', max_length=150, verbose_name='Cédula de Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default='N/A', max_length=150, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO')], default='Masculino', max_length=10, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='day',
            field=models.DateField(default='2024-01-09', max_length=50, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='permisology',
            name='day',
            field=models.DateField(default='2024-01-09', max_length=50, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='datejoined',
            field=models.DateField(default='2024-01-09', max_length=10, verbose_name='Fecha'),
        ),
    ]
